# Generated by Django 5.0.6 on 2024-06-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skDD_api', '0002_datahistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahistory',
            name='email',
        ),
    ]
